### ISSUE TITLE
Instead of a results box

### ISSUE THREAD

**Issue by nsanden** [nsanden/wordstopages#4]
Instead of a results box, lets highlight the areas that I bordered in red with a light blue or something to indicate that those are the results.

![highlight](https://cloud.githubusercontent.com/assets/2072064/10529773/b6290962-7355-11e5-83fd-8dd85df61270.png)

**Comment by shahzadthathal** [comment]
Design updated

**Comment by nsanden** [comment]
I do see the design is updated but I don't see any changes regarding this issue.

**Comment by shahzadthathal** [comment]
Highlight feature added

**Comment by nsanden** [comment]
Hmm... It wasn't exactly what I had in mind but I think it will work for now. I would like to change it from a red border though to a blue background.
![untitled](https://cloud.githubusercontent.com/assets/2072064/10667855/7985c872-788e-11e5-80df-afc75ad0ab0e.png)

**Comment by shahzadthathal** [comment]
Used background color instead of border.

**Comment by nsanden** [comment]
Looks good
