### ISSUE TITLE
Remaining Changes

### ISSUE THREAD

**Issue by nsanden** [nsanden/wordstopages#7]
- [ ] Remove the breadcrumbs "Home  How many pages required for specific words" - Not needed because this is going to be a one page website more or less.
- [ ] Tab Service One=Enter Total Number of Words
- [ ] Tab Service Two=Type in your Words
- [ ] HTML title = Words To Pages
- [ ] Copyright = (C) 2015 Words To Pages
- [ ] Instead of the bar below, lets remove it and instead put a Larger "Pages: [PAGENUM]"
![untitled](https://cloud.githubusercontent.com/assets/2072064/10668057/4990f9e2-788f-11e5-9e14-5deff0fd013d.png)

**Comment by shahzadthathal** [comment]
Changes fixed

**Comment by nsanden** [comment]
Missing copyright change.

Couple more changes:
- [ ] Change the new larger Pages: [ 0 ] background color to alert-info
- [ ] Remove the [  and ] from the Pages: [ 0 ]
- [ ] remove this gray box here 
![remove](https://cloud.githubusercontent.com/assets/2072064/10673557/5840857c-78ab-11e5-832f-90708dbdc150.png)

**Comment by shahzadthathal** [comment]
Fixed

**Comment by nsanden** [comment]
Another change
- [ ] On this website http://astrologycalculator.com/ we have 3 social media buttons. Can you add those to WordsToPages in the same way?

**Comment by shahzadthathal** [comment]
Social icon changed, web address needs to update
